package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model2.FindPassword;

import java.util.List;

public interface FindPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..find_password
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..find_password
     *
     * @mbg.generated
     */
    int insert(FindPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..find_password
     *
     * @mbg.generated
     */
    FindPassword selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..find_password
     *
     * @mbg.generated
     */
    List<FindPassword> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..find_password
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FindPassword record);
}