package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model.InterfaceWithBLOBs;
import com.kunlunsoft.model2.Interface;

import java.util.List;

public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    InterfaceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    List<Interface> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Interface record);
}