package com.kunlunsoft.mybatis.mapper2;

import org.apache.ibatis.annotations.Param;

import com.kunlunsoft.model2.Interface;

import java.util.List;

public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    Interface selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    List<Interface> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..interface
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Interface record);

    int updateResponseargsById(@Param("updatedResponseargs") String updatedResponseargs, @Param("id") String id);

    int updateResponseargsByName(@Param("updatedResponseargs") String updatedResponseargs, @Param("name") String name);

//    List<String> findResponseargsByName(@Param("name")String name);

    List<Interface> findByname(@Param("name") String name);

    List<Interface> findByUrlAndRequestmethod(@Param("url") String url, @Param("requestmethod") String requestmethod);

    List<Interface> findByUrl(@Param("url") String url);



}