package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model.ModuleWithBLOBs;
import com.kunlunsoft.model2.Module;

import java.util.List;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..module
     *
     * @mbg.generated
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..module
     *
     * @mbg.generated
     */
    ModuleWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..module
     *
     * @mbg.generated
     */
    List<Module> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Module record);
}