package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model2.ProjectUser;

import java.util.List;

public interface ProjectUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..project_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..project_user
     *
     * @mbg.generated
     */
    int insert(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..project_user
     *
     * @mbg.generated
     */
    ProjectUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..project_user
     *
     * @mbg.generated
     */
    List<ProjectUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..project_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectUser record);
}