package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model2.Share;

import java.util.List;

public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..share
     *
     * @mbg.generated
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..share
     *
     * @mbg.generated
     */
    Share selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..share
     *
     * @mbg.generated
     */
    List<Share> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Share record);
}