package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model2.Team;

import java.util.List;

public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team
     *
     * @mbg.generated
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team
     *
     * @mbg.generated
     */
    Team selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team
     *
     * @mbg.generated
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Team record);
}