package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model2.TeamUser;

import java.util.List;

public interface TeamUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team_user
     *
     * @mbg.generated
     */
    int insert(TeamUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team_user
     *
     * @mbg.generated
     */
    TeamUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team_user
     *
     * @mbg.generated
     */
    List<TeamUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..team_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeamUser record);
}