package com.kunlunsoft.mybatis.mapper2;

import com.kunlunsoft.model2.UserThird;

import java.util.List;

public interface UserThirdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..user_third
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..user_third
     *
     * @mbg.generated
     */
    int insert(UserThird record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..user_third
     *
     * @mbg.generated
     */
    UserThird selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..user_third
     *
     * @mbg.generated
     */
    List<UserThird> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoyaoji..user_third
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserThird record);
}