package com.kunlunsoft.model2;

import java.util.Date;

public class InterfaceFolder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface_folder.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface_folder.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface_folder.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface_folder.moduleId
     *
     * @mbg.generated
     */
    private String moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface_folder.projectId
     *
     * @mbg.generated
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface_folder.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface_folder.id
     *
     * @return the value of xiaoyaoji..interface_folder.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface_folder.id
     *
     * @param id the value for xiaoyaoji..interface_folder.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface_folder.name
     *
     * @return the value of xiaoyaoji..interface_folder.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface_folder.name
     *
     * @param name the value for xiaoyaoji..interface_folder.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface_folder.createTime
     *
     * @return the value of xiaoyaoji..interface_folder.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface_folder.createTime
     *
     * @param createtime the value for xiaoyaoji..interface_folder.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface_folder.moduleId
     *
     * @return the value of xiaoyaoji..interface_folder.moduleId
     * @mbg.generated
     */
    public String getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface_folder.moduleId
     *
     * @param moduleid the value for xiaoyaoji..interface_folder.moduleId
     * @mbg.generated
     */
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid == null ? null : moduleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface_folder.projectId
     *
     * @return the value of xiaoyaoji..interface_folder.projectId
     * @mbg.generated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface_folder.projectId
     *
     * @param projectid the value for xiaoyaoji..interface_folder.projectId
     * @mbg.generated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface_folder.sort
     *
     * @return the value of xiaoyaoji..interface_folder.sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface_folder.sort
     *
     * @param sort the value for xiaoyaoji..interface_folder.sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}