package com.kunlunsoft.model2;

import java.util.Date;

public class Interface {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.folderId
     *
     * @mbg.generated
     */
    private String folderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.requestMethod
     *
     * @mbg.generated
     */
    private String requestmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.contentType
     *
     * @mbg.generated
     */
    private String contenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.moduleId
     *
     * @mbg.generated
     */
    private String moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.projectId
     *
     * @mbg.generated
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.lastUpdateTime
     *
     * @mbg.generated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.dataType
     *
     * @mbg.generated
     */
    private String datatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.protocol
     *
     * @mbg.generated
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.requestHeaders
     *
     * @mbg.generated
     */
    private String requestheaders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.requestArgs
     *
     * @mbg.generated
     */
    private String requestargs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.responseArgs
     *
     * @mbg.generated
     */
    private String responseargs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..interface.example
     *
     * @mbg.generated
     */
    private String example;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.id
     *
     * @return the value of xiaoyaoji..interface.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.id
     *
     * @param id the value for xiaoyaoji..interface.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.name
     *
     * @return the value of xiaoyaoji..interface.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.name
     *
     * @param name the value for xiaoyaoji..interface.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.folderId
     *
     * @return the value of xiaoyaoji..interface.folderId
     * @mbg.generated
     */
    public String getFolderid() {
        return folderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.folderId
     *
     * @param folderid the value for xiaoyaoji..interface.folderId
     * @mbg.generated
     */
    public void setFolderid(String folderid) {
        this.folderid = folderid == null ? null : folderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.url
     *
     * @return the value of xiaoyaoji..interface.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.url
     *
     * @param url the value for xiaoyaoji..interface.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.requestMethod
     *
     * @return the value of xiaoyaoji..interface.requestMethod
     * @mbg.generated
     */
    public String getRequestmethod() {
        return requestmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.requestMethod
     *
     * @param requestmethod the value for xiaoyaoji..interface.requestMethod
     * @mbg.generated
     */
    public void setRequestmethod(String requestmethod) {
        this.requestmethod = requestmethod == null ? null : requestmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.contentType
     *
     * @return the value of xiaoyaoji..interface.contentType
     * @mbg.generated
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.contentType
     *
     * @param contenttype the value for xiaoyaoji..interface.contentType
     * @mbg.generated
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.moduleId
     *
     * @return the value of xiaoyaoji..interface.moduleId
     * @mbg.generated
     */
    public String getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.moduleId
     *
     * @param moduleid the value for xiaoyaoji..interface.moduleId
     * @mbg.generated
     */
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid == null ? null : moduleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.projectId
     *
     * @return the value of xiaoyaoji..interface.projectId
     * @mbg.generated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.projectId
     *
     * @param projectid the value for xiaoyaoji..interface.projectId
     * @mbg.generated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.lastUpdateTime
     *
     * @return the value of xiaoyaoji..interface.lastUpdateTime
     * @mbg.generated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.lastUpdateTime
     *
     * @param lastupdatetime the value for xiaoyaoji..interface.lastUpdateTime
     * @mbg.generated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.createTime
     *
     * @return the value of xiaoyaoji..interface.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.createTime
     *
     * @param createtime the value for xiaoyaoji..interface.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.dataType
     *
     * @return the value of xiaoyaoji..interface.dataType
     * @mbg.generated
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.dataType
     *
     * @param datatype the value for xiaoyaoji..interface.dataType
     * @mbg.generated
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype == null ? null : datatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.protocol
     *
     * @return the value of xiaoyaoji..interface.protocol
     * @mbg.generated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.protocol
     *
     * @param protocol the value for xiaoyaoji..interface.protocol
     * @mbg.generated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.status
     *
     * @return the value of xiaoyaoji..interface.status
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.status
     *
     * @param status the value for xiaoyaoji..interface.status
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.sort
     *
     * @return the value of xiaoyaoji..interface.sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.sort
     *
     * @param sort the value for xiaoyaoji..interface.sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.description
     *
     * @return the value of xiaoyaoji..interface.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.description
     *
     * @param description the value for xiaoyaoji..interface.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.requestHeaders
     *
     * @return the value of xiaoyaoji..interface.requestHeaders
     * @mbg.generated
     */
    public String getRequestheaders() {
        return requestheaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.requestHeaders
     *
     * @param requestheaders the value for xiaoyaoji..interface.requestHeaders
     * @mbg.generated
     */
    public void setRequestheaders(String requestheaders) {
        this.requestheaders = requestheaders == null ? null : requestheaders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.requestArgs
     *
     * @return the value of xiaoyaoji..interface.requestArgs
     * @mbg.generated
     */
    public String getRequestargs() {
        return requestargs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.requestArgs
     *
     * @param requestargs the value for xiaoyaoji..interface.requestArgs
     * @mbg.generated
     */
    public void setRequestargs(String requestargs) {
        this.requestargs = requestargs == null ? null : requestargs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.responseArgs
     *
     * @return the value of xiaoyaoji..interface.responseArgs
     * @mbg.generated
     */
    public String getResponseargs() {
        return responseargs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.responseArgs
     *
     * @param responseargs the value for xiaoyaoji..interface.responseArgs
     * @mbg.generated
     */
    public void setResponseargs(String responseargs) {
        this.responseargs = responseargs == null ? null : responseargs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..interface.example
     *
     * @return the value of xiaoyaoji..interface.example
     * @mbg.generated
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..interface.example
     *
     * @param example the value for xiaoyaoji..interface.example
     * @mbg.generated
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }
}