package com.kunlunsoft.model2;

import java.util.Date;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.lastUpdateTime
     *
     * @mbg.generated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.projectId
     *
     * @mbg.generated
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.requestHeaders
     *
     * @mbg.generated
     */
    private String requestheaders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..module.requestArgs
     *
     * @mbg.generated
     */
    private String requestargs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.id
     *
     * @return the value of xiaoyaoji..module.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.id
     *
     * @param id the value for xiaoyaoji..module.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.name
     *
     * @return the value of xiaoyaoji..module.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.name
     *
     * @param name the value for xiaoyaoji..module.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.host
     *
     * @return the value of xiaoyaoji..module.host
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.host
     *
     * @param host the value for xiaoyaoji..module.host
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.lastUpdateTime
     *
     * @return the value of xiaoyaoji..module.lastUpdateTime
     * @mbg.generated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.lastUpdateTime
     *
     * @param lastupdatetime the value for xiaoyaoji..module.lastUpdateTime
     * @mbg.generated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.projectId
     *
     * @return the value of xiaoyaoji..module.projectId
     * @mbg.generated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.projectId
     *
     * @param projectid the value for xiaoyaoji..module.projectId
     * @mbg.generated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.createTime
     *
     * @return the value of xiaoyaoji..module.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.createTime
     *
     * @param createtime the value for xiaoyaoji..module.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.sort
     *
     * @return the value of xiaoyaoji..module.sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.sort
     *
     * @param sort the value for xiaoyaoji..module.sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.description
     *
     * @return the value of xiaoyaoji..module.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.description
     *
     * @param description the value for xiaoyaoji..module.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.requestHeaders
     *
     * @return the value of xiaoyaoji..module.requestHeaders
     * @mbg.generated
     */
    public String getRequestheaders() {
        return requestheaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.requestHeaders
     *
     * @param requestheaders the value for xiaoyaoji..module.requestHeaders
     * @mbg.generated
     */
    public void setRequestheaders(String requestheaders) {
        this.requestheaders = requestheaders == null ? null : requestheaders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..module.requestArgs
     *
     * @return the value of xiaoyaoji..module.requestArgs
     * @mbg.generated
     */
    public String getRequestargs() {
        return requestargs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..module.requestArgs
     *
     * @param requestargs the value for xiaoyaoji..module.requestArgs
     * @mbg.generated
     */
    public void setRequestargs(String requestargs) {
        this.requestargs = requestargs == null ? null : requestargs.trim();
    }
}