package com.kunlunsoft.model2;

import java.util.Date;

public class ProjectLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project_log.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project_log.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project_log.projectId
     *
     * @mbg.generated
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project_log.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project_log.log
     *
     * @mbg.generated
     */
    private String log;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project_log.id
     *
     * @return the value of xiaoyaoji..project_log.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project_log.id
     *
     * @param id the value for xiaoyaoji..project_log.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project_log.userId
     *
     * @return the value of xiaoyaoji..project_log.userId
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project_log.userId
     *
     * @param userid the value for xiaoyaoji..project_log.userId
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project_log.createTime
     *
     * @return the value of xiaoyaoji..project_log.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project_log.createTime
     *
     * @param createtime the value for xiaoyaoji..project_log.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project_log.projectId
     *
     * @return the value of xiaoyaoji..project_log.projectId
     * @mbg.generated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project_log.projectId
     *
     * @param projectid the value for xiaoyaoji..project_log.projectId
     * @mbg.generated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project_log.action
     *
     * @return the value of xiaoyaoji..project_log.action
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project_log.action
     *
     * @param action the value for xiaoyaoji..project_log.action
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project_log.log
     *
     * @return the value of xiaoyaoji..project_log.log
     * @mbg.generated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project_log.log
     *
     * @param log the value for xiaoyaoji..project_log.log
     * @mbg.generated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }
}