package com.kunlunsoft.model2;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.teamId
     *
     * @mbg.generated
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.permission
     *
     * @mbg.generated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.environments
     *
     * @mbg.generated
     */
    private String environments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..project.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.id
     *
     * @return the value of xiaoyaoji..project.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.id
     *
     * @param id the value for xiaoyaoji..project.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.name
     *
     * @return the value of xiaoyaoji..project.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.name
     *
     * @param name the value for xiaoyaoji..project.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.description
     *
     * @return the value of xiaoyaoji..project.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.description
     *
     * @param description the value for xiaoyaoji..project.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.teamId
     *
     * @return the value of xiaoyaoji..project.teamId
     * @mbg.generated
     */
    public String getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.teamId
     *
     * @param teamid the value for xiaoyaoji..project.teamId
     * @mbg.generated
     */
    public void setTeamid(String teamid) {
        this.teamid = teamid == null ? null : teamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.createTime
     *
     * @return the value of xiaoyaoji..project.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.createTime
     *
     * @param createtime the value for xiaoyaoji..project.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.userId
     *
     * @return the value of xiaoyaoji..project.userId
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.userId
     *
     * @param userid the value for xiaoyaoji..project.userId
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.status
     *
     * @return the value of xiaoyaoji..project.status
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.status
     *
     * @param status the value for xiaoyaoji..project.status
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.permission
     *
     * @return the value of xiaoyaoji..project.permission
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.permission
     *
     * @param permission the value for xiaoyaoji..project.permission
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.environments
     *
     * @return the value of xiaoyaoji..project.environments
     * @mbg.generated
     */
    public String getEnvironments() {
        return environments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.environments
     *
     * @param environments the value for xiaoyaoji..project.environments
     * @mbg.generated
     */
    public void setEnvironments(String environments) {
        this.environments = environments == null ? null : environments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..project.details
     *
     * @return the value of xiaoyaoji..project.details
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..project.details
     *
     * @param details the value for xiaoyaoji..project.details
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}