package com.kunlunsoft.model2;

import java.util.Date;

public class Share {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.shareAll
     *
     * @mbg.generated
     */
    private String shareall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.moduleIds
     *
     * @mbg.generated
     */
    private String moduleids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..share.projectId
     *
     * @mbg.generated
     */
    private String projectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.id
     *
     * @return the value of xiaoyaoji..share.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.id
     *
     * @param id the value for xiaoyaoji..share.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.name
     *
     * @return the value of xiaoyaoji..share.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.name
     *
     * @param name the value for xiaoyaoji..share.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.createTime
     *
     * @return the value of xiaoyaoji..share.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.createTime
     *
     * @param createtime the value for xiaoyaoji..share.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.userId
     *
     * @return the value of xiaoyaoji..share.userId
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.userId
     *
     * @param userid the value for xiaoyaoji..share.userId
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.shareAll
     *
     * @return the value of xiaoyaoji..share.shareAll
     * @mbg.generated
     */
    public String getShareall() {
        return shareall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.shareAll
     *
     * @param shareall the value for xiaoyaoji..share.shareAll
     * @mbg.generated
     */
    public void setShareall(String shareall) {
        this.shareall = shareall == null ? null : shareall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.password
     *
     * @return the value of xiaoyaoji..share.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.password
     *
     * @param password the value for xiaoyaoji..share.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.moduleIds
     *
     * @return the value of xiaoyaoji..share.moduleIds
     * @mbg.generated
     */
    public String getModuleids() {
        return moduleids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.moduleIds
     *
     * @param moduleids the value for xiaoyaoji..share.moduleIds
     * @mbg.generated
     */
    public void setModuleids(String moduleids) {
        this.moduleids = moduleids == null ? null : moduleids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..share.projectId
     *
     * @return the value of xiaoyaoji..share.projectId
     * @mbg.generated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..share.projectId
     *
     * @param projectid the value for xiaoyaoji..share.projectId
     * @mbg.generated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }
}