package com.kunlunsoft.model2;

import java.util.Date;

public class TeamUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..team_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..team_user.teamId
     *
     * @mbg.generated
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..team_user.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoyaoji..team_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..team_user.id
     *
     * @return the value of xiaoyaoji..team_user.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..team_user.id
     *
     * @param id the value for xiaoyaoji..team_user.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..team_user.teamId
     *
     * @return the value of xiaoyaoji..team_user.teamId
     * @mbg.generated
     */
    public String getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..team_user.teamId
     *
     * @param teamid the value for xiaoyaoji..team_user.teamId
     * @mbg.generated
     */
    public void setTeamid(String teamid) {
        this.teamid = teamid == null ? null : teamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..team_user.userId
     *
     * @return the value of xiaoyaoji..team_user.userId
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..team_user.userId
     *
     * @param userid the value for xiaoyaoji..team_user.userId
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoyaoji..team_user.createTime
     *
     * @return the value of xiaoyaoji..team_user.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoyaoji..team_user.createTime
     *
     * @param createtime the value for xiaoyaoji..team_user.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}